#!/opt/python/bin/python3

import sys
import subprocess

# wpa_cli -i wlan0 status; wpa_cli -i wlan0 signal_poll
status = """
bssid=dc:fe:07:b8:63:80
freq=2462
ssid=Emarhavil
id=0
mode=station
pairwise_cipher=CCMP
group_cipher=CCMP
key_mgmt=WPA2-PSK
wpa_state=COMPLETED
ip_address=10.1.10.164
p2p_device_address=0a:fb:ea:03:e2:e8
address=08:fb:ea:03:e2:e8
uuid=722a4b17-5d01-5585-a6c3-5d400c46b828
RSSI=-36
LINKSPEED=72
NOISE=9999
FREQUENCY=2462
"""

try:
    status = subprocess.run("wpa_cli -i wlan0 status; wpa_cli -i wlan0 signal_poll", shell=True, check=True, capture_output=True).stdout.decode()
except:
    print("wpa_cli returned error; something is wrong")
    sys.exit(1)

"""
wlan0     IEEE 802.11  ESSID:"Emarhavil"  
          Mode:Master  Frequency:2.462 GHz  Access Point: DC:FE:07:B8:63:80   
          Bit Rate=72 Mb/s   Tx-Power:32 dBm   
          Retry min limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=5/5  Signal level=-35 dBm  Noise level=-89 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
"""

fields = { v.split('=')[0]: v.split('=')[1] for v in status.strip().split('\n') }

if 'bssid' not in fields:
    print(f"""wlan0     IEEE 802.11  ESSID:"{fields.get('ssid','')}"
          Mode:Managed   Access Point: Not-Associated   Tx-Power:32 dBm  <- this power number is fake, use iw
          Retry min limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
""")
else:
    print(f"""wlan0     IEEE 802.11  ESSID:"{fields['ssid']}"
          Mode:Master  Frequency:{float(fields['freq'])/1000} GHz  Access Point: {fields['bssid'].upper()}
          Bit Rate={fields['LINKSPEED']} Mb/s   Tx-Power:32 dBm
          Retry min limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=5/5  Signal level={fields['RSSI']} dBm  Noise level=-89 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
          some of these numbers are fake; this iwconfig is a python wrapper to keep various Bambu components happy, and you should just use iw if you care
""")
    
