#!/bin/sh

# X1Plus boot script
#
# Copyright (c) 2023 - 2024 Joshua Wise, and the X1Plus authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PATH=/:/bin

mkdir /dev
mknod /dev/mmcblk2p1 b 179 97
mknod /dev/loop-control c 10 237
mknod /dev/loop0 b 7 0
mknod /dev/loop1 b 7 1
mknod /dev/loop2 b 7 2
mknod /dev/loop3 b 7 3
mknod /dev/loop4 b 7 4
mknod /dev/loop5 b 7 5
mknod /dev/loop6 b 7 6
mknod /dev/loop7 b 7 7
mknod /dev/tty0 c 4 0
mknod /dev/fb0 c 29 0

loadfont < /ter-i32b.psf
echo -en "\e[8;1H" > /dev/tty0
gzip -c -d /bootlogo.dat.gz > /dev/fb0
# cat /signon > /dev/tty0
echo "Initializing X1Plus filesystems." > /dev/tty0

# probably show something on screen if we fail?
echo "init params $*"

mkdir /fs
mount -t tmpfs none /fs

mkdir /proc
mount -t proc /proc /proc

VERBOSE_BOOT=$(cat /proc/cmdline | xargs -n1 | grep "=" | sed "s|x1plus_debug=||")
if [ "$VERBOSE_BOOT" -eq "true" ] ; then
	echo "Starting verbose boot mode" > /dev/tty0
	{ 
	. init-stage2
	} > /dev/tty0 2>&1
else
    . init-stage2
fi
