#!/usr/bin/env bash
echo Killing nuisances...
sshpass -p "$2" ssh root@"$1" 'kill $(cat /var/run/screen_service.pid); kill $(pidof bbl_screen)'
echo Uploading...
sshpass -p "$2" scp printer_ui.so root@"$1":/opt/
echo Running...
sshpass -p "$2" ssh root@"$1" "bbl_screen"