#!/bin/sh

start() {
	printf "Starting sd_watchdog"
	start-stop-daemon -S -m -b -p /var/run/sd_watchdog.pid --exec x1plus.services.sd_watchdog
}
stop() {
	printf "Stopping sd_watchdog"
	start-stop-daemon -K -q -p /var/run/sd_watchdog.pid
        rm -f /var/run/sd_watchdog.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
        sleep 5
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
