#!/bin/sh

# X1Plus Daemon, our Python do-it-all script that interfaces with DDS.

start() {
	printf "Starting x1plusd: "
	start-stop-daemon -S -m -b -p /var/run/x1plusd.pid --exec /opt/python/bin/python3 -- /opt/x1plusd.py
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping x1plusd: "
	start-stop-daemon -K -q -p /var/run/x1plusd.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
    sleep 5
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
