#!/bin/sh

# The X1Plus Service, our Python do-it-all daemon

start() {
	printf "Starting X1Plus service: "
	start-stop-daemon -S -m -b -p /var/run/x1plus_service.pid --exec /opt/python/bin/python3 -- /opt/x1plus_service.py
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping X1Plus service: "
	start-stop-daemon -K -q -p /var/run/x1plus_service.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
    sleep 5
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
