#!/bin/sh

start() {
	printf "Grabbing gpiokeys"
	start-stop-daemon -S -m -b -p /var/run/gpiokeys.pid --exec /opt/python/bin/python3 -- -m x1plus.services.gpiokeys
}
stop() {
	printf "Ungrabbing gpiokeys"
	start-stop-daemon -K -q -p /var/run/gpiokeys.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
    #sleep 0.5
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?