#!/bin/sh

start() {
	printf "Starting forward service: "
	/bin/touch /tmp/bbl_crypto
	export LD_PRELOAD=/opt/x1plus/lib/forward_shim.so
	start-stop-daemon -S -m -b -p /var/run/forward_service.pid \
		--exec /usr/bin/forward \
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping forward service: "
	start-stop-daemon -K -q -p /var/run/forward_service.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
    sleep 5
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
